<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.A3P0lzd' shared service.

return $this->privates['.service_locator.A3P0lzd'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'entity' => ['privates', '.errored..service_locator.A3P0lzd.App\\Entity\\BlogContent', NULL, 'Cannot autowire service ".service_locator.A3P0lzd": it references class "App\\Entity\\BlogContent" but no such service exists.'],
]);
