App\Entity\BlogContent:
  constraints:
    - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: title
  properties:
    id_cat:
      - Range:
          min: 1
          max: 10
      - NotBlank: ~
      - NotNull: ~
    author:
      - Length:
          min: 4
          max: 50
          minMessage: min 4 max 50
          maxMessage: min 4 max 50
      - NotBlank: ~
      - NotNull: ~
    title:
      - Length:
          min: 15
          max: 255
      - NotBlank: ~
      - NotNull: ~

App\Entity\BlogCategories:
  constraints:
    - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: name
  properties:
    name:
      - Length:
          min: 1
          max: 255
      - NotBlank: ~
      - NotNull: ~
    img:
      - Regex:
          #match -> name.abc | na_me.abc
          pattern: '/^(\w*)(\.)([a-z]{3})$/'
      - Length:
          min: 5
          max: 255
      - NotBlank: ~
      - NotNull: ~

App\Entity\BlogUser:
  constraints:
    - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: username
  properties:
    username:
      - NotBlank: ~
      - NotNull: ~
    password:
      - NotBlank: ~
      - NotNull: ~
