#index:
#    path: /
#    controller: App\Controller\DefaultController::index

home:
  path: /
  controller: App\Controller\HomeController::index

blog.unique:
  path: /blog/{slug}-{id}
  controller: App\Controller\BlogController::unique
  requirements:
    slug: '[a-z 0-9 \-]*'

admin:
  path: /admin
  controller: App\Controller\Admin\AdminBlogController::index

admin.unique.new:
  path: /admin/new-blog-entry
  controller: App\Controller\Admin\AdminBlogController::new

admin.unique.edit:
  path: /admin/modif-{slug}-{id}
  controller: App\Controller\Admin\AdminBlogController::edit
  requirements:
    slug: '[a-z 0-9 \-]*'
  methods: [GET, POST]

admin.unique.delete:
  path: /admin/modif-{slug}-{id}
  controller: App\Controller\Admin\AdminBlogController::delete
  requirements:
    slug: '[a-z 0-9 \-]*'
  methods: [DELETE]

