#index:
#    path: /
#    controller: App\Controller\DefaultController::index

home:
  path: /
  controller: App\Controller\HomeController::index

blog.unique:
  path: /blog/{slug}-{id}
  controller: App\Controller\BlogController::unique
  requirements:
    slug: '[a-z 0-9 \-]*'

admin:
  path: /admin
  controller: App\Controller\Admin\AdminBlogController::index

admin.unique:
  path: /admin/modif-{slug}-{id}
  controller: App\Controller\Admin\AdminBlogController::unique
  requirements:
    slug: '[a-z 0-9 \-]*'