# front
home:
  path: /
  controller: App\Controller\HomeController::index

blog.unique:
  path: /blog/{slug}-{id}
  controller: App\Controller\BlogController::unique
  requirements:
    slug: '[a-z 0-9 \-]*'

# back
admin:
  path: /admin
  controller: App\Controller\Admin\AdminBlogController::index

# blog
admin.unique.new:
  path: /admin/new-blog-entry
  controller: App\Controller\Admin\AdminBlogController::new

admin.unique.edit:
  path: /admin/modif-{slug}-{id}
  controller: App\Controller\Admin\AdminBlogController::edit
  requirements:
    slug: '[a-z 0-9 \-]*'
  methods: [GET, POST]

admin.unique.delete:
  path: /admin/modif-{slug}-{id}
  controller: App\Controller\Admin\AdminBlogController::delete
  requirements:
    slug: '[a-z 0-9 \-]*'
  methods: [DELETE]

# user
admin.user:
  path: /admin/user
  controller: App\Controller\Admin\AdminUserController::index

admin.user.new:
  path: /admin/new-user-entry
  controller: App\Controller\Admin\AdminUserController::new

admin.user.edit: #not work - dispatch to index
  path: /admin/user
  controller: App\Controller\Admin\AdminUserController::index
  methods: [GET, POST]

admin.user.delete:
  path: /admin/modif-{id}
  controller: App\Controller\Admin\AdminUserController::delete
  methods: [DELETE]

# authenticate
login:
  path: /login
  controller: App\Controller\Admin\AdminAuthenticationController::login

logout:
  path: /logout