<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerC5xO4An\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerC5xO4An/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerC5xO4An.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerC5xO4An\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerC5xO4An\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'C5xO4An',
    'container.build_id' => '0f6af673',
    'container.build_time' => 1550581898,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerC5xO4An');
