<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'Symfony.Component.Form.Form' => 0,
'IteratorAggregate' => 1,
'Traversable' => 2,
'Symfony.Component.Form.FormInterface' => 3,
'ArrayAccess' => 4,
'Countable' => 5,
'Symfony.Component.Form.ClearableErrorsInterface' => 6,
'App.Entity.BlogContent' => 7,
'App.Entity.BlogCategories' => 8,
'App.Entity.BlogUser' => 9,
'Symfony.Component.Security.Core.User.UserInterface' => 10,
'Serializable' => 11,

], [

0 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            (($f = &\Symfony\Component\VarExporter\Internal\Registry::$factories)['Symfony\\Component\\Validator\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::f('Symfony\\Component\\Validator\\Mapping\\ClassMetadata'))(),
            ($f['Symfony\\Component\\Validator\\Mapping\\PropertyMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::f('Symfony\\Component\\Validator\\Mapping\\PropertyMetadata'))(),
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Symfony\\Component\\Form\\Extension\\Validator\\Constraints\\Form'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Form\\Extension\\Validator\\Constraints\\Form')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'Symfony\\Component\\Form\\Form',
                    'children',
                ],
                'defaultGroup' => [
                    'Form',
                ],
                'members' => [
                    [
                        'children' => [
                            $o[1],
                        ],
                    ],
                ],
                'properties' => [
                    [
                        'children' => $o[1],
                    ],
                ],
                'constraints' => [
                    [
                        $o[2],
                    ],
                ],
                'constraintsByGroup' => [
                    [
                        'Default' => [
                            $o[2],
                        ],
                        'Form' => [
                            $o[2],
                        ],
                    ],
                ],
                'class' => [
                    1 => 'Symfony\\Component\\Form\\Form',
                ],
                'property' => [
                    1 => 'children',
                ],
                'cascadingStrategy' => [
                    1 => 2,
                ],
                'traversalStrategy' => [
                    1 => 1,
                ],
                'groups' => [
                    2 => [
                        'Default',
                        'Form',
                    ],
                ],
            ],
        ],
        $o[0],
        []
    );
},
1 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            (\Symfony\Component\VarExporter\Internal\Registry::$factories['Symfony\\Component\\Validator\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::f('Symfony\\Component\\Validator\\Mapping\\ClassMetadata'))(),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'IteratorAggregate',
                ],
                'defaultGroup' => [
                    'IteratorAggregate',
                ],
            ],
        ],
        $o[0],
        []
    );
},
2 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            (\Symfony\Component\VarExporter\Internal\Registry::$factories['Symfony\\Component\\Validator\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::f('Symfony\\Component\\Validator\\Mapping\\ClassMetadata'))(),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'Traversable',
                ],
                'defaultGroup' => [
                    'Traversable',
                ],
            ],
        ],
        $o[0],
        []
    );
},
3 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            (\Symfony\Component\VarExporter\Internal\Registry::$factories['Symfony\\Component\\Validator\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::f('Symfony\\Component\\Validator\\Mapping\\ClassMetadata'))(),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'Symfony\\Component\\Form\\FormInterface',
                ],
                'defaultGroup' => [
                    'FormInterface',
                ],
            ],
        ],
        $o[0],
        []
    );
},
4 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            (\Symfony\Component\VarExporter\Internal\Registry::$factories['Symfony\\Component\\Validator\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::f('Symfony\\Component\\Validator\\Mapping\\ClassMetadata'))(),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'ArrayAccess',
                ],
                'defaultGroup' => [
                    'ArrayAccess',
                ],
            ],
        ],
        $o[0],
        []
    );
},
5 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            (\Symfony\Component\VarExporter\Internal\Registry::$factories['Symfony\\Component\\Validator\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::f('Symfony\\Component\\Validator\\Mapping\\ClassMetadata'))(),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'Countable',
                ],
                'defaultGroup' => [
                    'Countable',
                ],
            ],
        ],
        $o[0],
        []
    );
},
6 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            (\Symfony\Component\VarExporter\Internal\Registry::$factories['Symfony\\Component\\Validator\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::f('Symfony\\Component\\Validator\\Mapping\\ClassMetadata'))(),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'Symfony\\Component\\Form\\ClearableErrorsInterface',
                ],
                'defaultGroup' => [
                    'ClearableErrorsInterface',
                ],
            ],
        ],
        $o[0],
        []
    );
},
7 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            (($f = &\Symfony\Component\VarExporter\Internal\Registry::$factories)['Symfony\\Component\\Validator\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::f('Symfony\\Component\\Validator\\Mapping\\ClassMetadata'))(),
            ($f['Symfony\\Component\\Validator\\Mapping\\PropertyMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::f('Symfony\\Component\\Validator\\Mapping\\PropertyMetadata'))(),
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Symfony\\Component\\Validator\\Constraints\\Range'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Validator\\Constraints\\Range')),
            clone ($p['Symfony\\Component\\Validator\\Constraints\\NotBlank'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Validator\\Constraints\\NotBlank')),
            clone ($p['Symfony\\Component\\Validator\\Constraints\\NotNull'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Validator\\Constraints\\NotNull')),
            $f['Symfony\\Component\\Validator\\Mapping\\PropertyMetadata'](),
            clone ($p['Symfony\\Component\\Validator\\Constraints\\Length'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Validator\\Constraints\\Length')),
            clone $p['Symfony\\Component\\Validator\\Constraints\\NotBlank'],
            clone $p['Symfony\\Component\\Validator\\Constraints\\NotNull'],
            $f['Symfony\\Component\\Validator\\Mapping\\PropertyMetadata'](),
            clone $p['Symfony\\Component\\Validator\\Constraints\\Length'],
            clone $p['Symfony\\Component\\Validator\\Constraints\\NotBlank'],
            clone $p['Symfony\\Component\\Validator\\Constraints\\NotNull'],
            clone ($p['Symfony\\Bridge\\Doctrine\\Validator\\Constraints\\UniqueEntity'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Bridge\\Doctrine\\Validator\\Constraints\\UniqueEntity')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'App\\Entity\\BlogContent',
                    'id_cat',
                    5 => 'author',
                    9 => 'title',
                ],
                'defaultGroup' => [
                    'BlogContent',
                ],
                'members' => [
                    [
                        'id_cat' => [
                            $o[1],
                        ],
                        'author' => [
                            $o[5],
                        ],
                        'title' => [
                            $o[9],
                        ],
                    ],
                ],
                'properties' => [
                    [
                        'id_cat' => $o[1],
                        'author' => $o[5],
                        'title' => $o[9],
                    ],
                ],
                'constraints' => [
                    [
                        $o[13],
                    ],
                    [
                        $o[2],
                        $o[3],
                        $o[4],
                    ],
                    5 => [
                        $o[6],
                        $o[7],
                        $o[8],
                    ],
                    9 => [
                        $o[10],
                        $o[11],
                        $o[12],
                    ],
                ],
                'constraintsByGroup' => [
                    [
                        'Default' => [
                            $o[13],
                        ],
                        'BlogContent' => [
                            $o[13],
                        ],
                    ],
                    [
                        'Default' => [
                            $o[2],
                            $o[3],
                            $o[4],
                        ],
                        'BlogContent' => [
                            $o[2],
                            $o[3],
                            $o[4],
                        ],
                    ],
                    5 => [
                        'Default' => [
                            $o[6],
                            $o[7],
                            $o[8],
                        ],
                        'BlogContent' => [
                            $o[6],
                            $o[7],
                            $o[8],
                        ],
                    ],
                    9 => [
                        'Default' => [
                            $o[10],
                            $o[11],
                            $o[12],
                        ],
                        'BlogContent' => [
                            $o[10],
                            $o[11],
                            $o[12],
                        ],
                    ],
                ],
                'class' => [
                    1 => 'App\\Entity\\BlogContent',
                    5 => 'App\\Entity\\BlogContent',
                    9 => 'App\\Entity\\BlogContent',
                ],
                'property' => [
                    1 => 'id_cat',
                    5 => 'author',
                    9 => 'title',
                ],
                'min' => [
                    2 => 1,
                    6 => 4,
                    10 => 15,
                ],
                'max' => [
                    2 => 10,
                    6 => 50,
                    10 => 255,
                ],
                'groups' => [
                    2 => [
                        'Default',
                        'BlogContent',
                    ],
                    [
                        'Default',
                        'BlogContent',
                    ],
                    [
                        'Default',
                        'BlogContent',
                    ],
                    6 => [
                        'Default',
                        'BlogContent',
                    ],
                    [
                        'Default',
                        'BlogContent',
                    ],
                    [
                        'Default',
                        'BlogContent',
                    ],
                    10 => [
                        'Default',
                        'BlogContent',
                    ],
                    [
                        'Default',
                        'BlogContent',
                    ],
                    [
                        'Default',
                        'BlogContent',
                    ],
                    [
                        'Default',
                        'BlogContent',
                    ],
                ],
                'maxMessage' => [
                    6 => 'min 4 max 50',
                ],
                'minMessage' => [
                    6 => 'min 4 max 50',
                ],
                'fields' => [
                    13 => 'title',
                ],
            ],
        ],
        $o[0],
        []
    );
},
8 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            (($f = &\Symfony\Component\VarExporter\Internal\Registry::$factories)['Symfony\\Component\\Validator\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::f('Symfony\\Component\\Validator\\Mapping\\ClassMetadata'))(),
            ($f['Symfony\\Component\\Validator\\Mapping\\PropertyMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::f('Symfony\\Component\\Validator\\Mapping\\PropertyMetadata'))(),
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Symfony\\Component\\Validator\\Constraints\\Length'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Validator\\Constraints\\Length')),
            clone ($p['Symfony\\Component\\Validator\\Constraints\\NotBlank'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Validator\\Constraints\\NotBlank')),
            clone ($p['Symfony\\Component\\Validator\\Constraints\\NotNull'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Validator\\Constraints\\NotNull')),
            $f['Symfony\\Component\\Validator\\Mapping\\PropertyMetadata'](),
            clone ($p['Symfony\\Component\\Validator\\Constraints\\Regex'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Validator\\Constraints\\Regex')),
            clone $p['Symfony\\Component\\Validator\\Constraints\\Length'],
            clone $p['Symfony\\Component\\Validator\\Constraints\\NotBlank'],
            clone $p['Symfony\\Component\\Validator\\Constraints\\NotNull'],
            clone ($p['Symfony\\Bridge\\Doctrine\\Validator\\Constraints\\UniqueEntity'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Bridge\\Doctrine\\Validator\\Constraints\\UniqueEntity')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'App\\Entity\\BlogCategories',
                    'name',
                    5 => 'img',
                ],
                'defaultGroup' => [
                    'BlogCategories',
                ],
                'members' => [
                    [
                        'name' => [
                            $o[1],
                        ],
                        'img' => [
                            $o[5],
                        ],
                    ],
                ],
                'properties' => [
                    [
                        'name' => $o[1],
                        'img' => $o[5],
                    ],
                ],
                'constraints' => [
                    [
                        $o[10],
                    ],
                    [
                        $o[2],
                        $o[3],
                        $o[4],
                    ],
                    5 => [
                        $o[6],
                        $o[7],
                        $o[8],
                        $o[9],
                    ],
                ],
                'constraintsByGroup' => [
                    [
                        'Default' => [
                            $o[10],
                        ],
                        'BlogCategories' => [
                            $o[10],
                        ],
                    ],
                    [
                        'Default' => [
                            $o[2],
                            $o[3],
                            $o[4],
                        ],
                        'BlogCategories' => [
                            $o[2],
                            $o[3],
                            $o[4],
                        ],
                    ],
                    5 => [
                        'Default' => [
                            $o[6],
                            $o[7],
                            $o[8],
                            $o[9],
                        ],
                        'BlogCategories' => [
                            $o[6],
                            $o[7],
                            $o[8],
                            $o[9],
                        ],
                    ],
                ],
                'class' => [
                    1 => 'App\\Entity\\BlogCategories',
                    5 => 'App\\Entity\\BlogCategories',
                ],
                'property' => [
                    1 => 'name',
                    5 => 'img',
                ],
                'max' => [
                    2 => 255,
                    7 => 255,
                ],
                'min' => [
                    2 => 1,
                    7 => 5,
                ],
                'groups' => [
                    2 => [
                        'Default',
                        'BlogCategories',
                    ],
                    [
                        'Default',
                        'BlogCategories',
                    ],
                    [
                        'Default',
                        'BlogCategories',
                    ],
                    6 => [
                        'Default',
                        'BlogCategories',
                    ],
                    [
                        'Default',
                        'BlogCategories',
                    ],
                    [
                        'Default',
                        'BlogCategories',
                    ],
                    [
                        'Default',
                        'BlogCategories',
                    ],
                    [
                        'Default',
                        'BlogCategories',
                    ],
                ],
                'pattern' => [
                    6 => '/^(\\w*)(\\.)([a-z]{3})$/',
                ],
                'fields' => [
                    10 => 'name',
                ],
            ],
        ],
        $o[0],
        []
    );
},
9 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            (($f = &\Symfony\Component\VarExporter\Internal\Registry::$factories)['Symfony\\Component\\Validator\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::f('Symfony\\Component\\Validator\\Mapping\\ClassMetadata'))(),
            ($f['Symfony\\Component\\Validator\\Mapping\\PropertyMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::f('Symfony\\Component\\Validator\\Mapping\\PropertyMetadata'))(),
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Symfony\\Component\\Validator\\Constraints\\NotBlank'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Validator\\Constraints\\NotBlank')),
            clone ($p['Symfony\\Component\\Validator\\Constraints\\NotNull'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Validator\\Constraints\\NotNull')),
            $f['Symfony\\Component\\Validator\\Mapping\\PropertyMetadata'](),
            clone $p['Symfony\\Component\\Validator\\Constraints\\NotBlank'],
            clone $p['Symfony\\Component\\Validator\\Constraints\\NotNull'],
            clone ($p['Symfony\\Bridge\\Doctrine\\Validator\\Constraints\\UniqueEntity'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Bridge\\Doctrine\\Validator\\Constraints\\UniqueEntity')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'App\\Entity\\BlogUser',
                    'username',
                    4 => 'password',
                ],
                'defaultGroup' => [
                    'BlogUser',
                ],
                'members' => [
                    [
                        'username' => [
                            $o[1],
                        ],
                        'password' => [
                            $o[4],
                        ],
                    ],
                ],
                'properties' => [
                    [
                        'username' => $o[1],
                        'password' => $o[4],
                    ],
                ],
                'constraints' => [
                    [
                        $o[7],
                    ],
                    [
                        $o[2],
                        $o[3],
                    ],
                    4 => [
                        $o[5],
                        $o[6],
                    ],
                ],
                'constraintsByGroup' => [
                    [
                        'Default' => [
                            $o[7],
                        ],
                        'BlogUser' => [
                            $o[7],
                        ],
                    ],
                    [
                        'Default' => [
                            $o[2],
                            $o[3],
                        ],
                        'BlogUser' => [
                            $o[2],
                            $o[3],
                        ],
                    ],
                    4 => [
                        'Default' => [
                            $o[5],
                            $o[6],
                        ],
                        'BlogUser' => [
                            $o[5],
                            $o[6],
                        ],
                    ],
                ],
                'class' => [
                    1 => 'App\\Entity\\BlogUser',
                    4 => 'App\\Entity\\BlogUser',
                ],
                'property' => [
                    1 => 'username',
                    4 => 'password',
                ],
                'groups' => [
                    2 => [
                        'Default',
                        'BlogUser',
                    ],
                    [
                        'Default',
                        'BlogUser',
                    ],
                    5 => [
                        'Default',
                        'BlogUser',
                    ],
                    [
                        'Default',
                        'BlogUser',
                    ],
                    [
                        'Default',
                        'BlogUser',
                    ],
                ],
                'fields' => [
                    7 => 'username',
                ],
            ],
        ],
        $o[0],
        []
    );
},
10 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            (\Symfony\Component\VarExporter\Internal\Registry::$factories['Symfony\\Component\\Validator\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::f('Symfony\\Component\\Validator\\Mapping\\ClassMetadata'))(),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'Symfony\\Component\\Security\\Core\\User\\UserInterface',
                ],
                'defaultGroup' => [
                    'UserInterface',
                ],
            ],
        ],
        $o[0],
        []
    );
},
11 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            (\Symfony\Component\VarExporter\Internal\Registry::$factories['Symfony\\Component\\Validator\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::f('Symfony\\Component\\Validator\\Mapping\\ClassMetadata'))(),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'Serializable',
                ],
                'defaultGroup' => [
                    'Serializable',
                ],
            ],
        ],
        $o[0],
        []
    );
},

]];
