<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.QdSwBri' shared service.

return $this->privates['.service_locator.QdSwBri'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'notification' => ['privates', 'App\\Notification\\ContactNotification', 'getContactNotificationService.php', true],
]);
