<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.vAywuIp' shared service.

return $this->privates['.service_locator.vAywuIp'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'entity' => ['privates', '.errored..service_locator.vAywuIp.App\\Entity\\BlogUser', NULL, 'Cannot autowire service ".service_locator.vAywuIp": it references class "App\\Entity\\BlogUser" but no such service exists.'],
]);
